### DISCUSSION TITLE
Change Tooltip Style Base on Gutter Annotation Type?

### DISCUSSION THREAD

**Discussion by KiddoV** [ajaxorg/ace#4710] [Q&A] [answered]
Is there anyway that I can change the tooltip style base on annotation condition?
For example: if gutter is error type I would like to add an ``error`` class to the ``ace_tooltip``, if it is info add ``info`` class to ``ace_tooltip``.
So that I can style each tooltip in ``CSS`` like so:
```CSS
.ace_tooltip.error {
    color: red;
}
.ace_tooltip.blue{
    color: blue;
}
....
```

Thanks!
