### ISSUE TITLE
Invalid number value breaks CSS mode

### ISSUE THREAD

**Issue by fjakobs** [ajaxorg/ace#1413]
try pasting 

``` css
div {
    width: 3S50px;
}
```

into an ace document in CSS mode. It will completely break the editor.
