### ISSUE TITLE
Pipe '|' symbol breaks YAML Syntax highlighting

### ISSUE THREAD

**Issue by daeks** [ajaxorg/ace#1598]
just referencing a "bug" found in our project Codiad https://github.com/Codiad/Codiad/issues/480

Pipe '|' symbol breaks YAML Syntax highlighting with example yaml

```
groups:
  Guest:
    default: true
    prefix: '&7[&fG&7]&f '
    options:
      rank: '1000'
    permissions:
    - test.ok.*
    - test.fails.here(|.*)
    - all.entries.after.show.as.bad.syntax
```
