### ISSUE TITLE
Strange warning from CSS lint on flex and -webkit-flex properties

### ISSUE THREAD

**Issue by felicienfrancois** [ajaxorg/ace#2072]
I get the following warning:

```
this.complex[type] is not a function
```

To reproduce: http://ace.c9.io/build/kitchen-sink.html

``` css
.test {
    -webkit-flex: 1;
    flex: 1;
}
```
