### ISSUE TITLE
Displaying top of ace_bracket

### ISSUE THREAD

**Issue by xixixao** [ajaxorg/ace#2149]
The style for highlighting matching brackets looks usually like:

``` css
.ace_marker-layer .ace_bracket {
    margin: -1px 0 0 -1px;
    border: 1px solid rgba(255, 255, 255, 0.15)
  }
```

But this means the top border will be cut off on the first line. I am trying to muck around with CSS to get it to display (note that I have ace inside a padded area, so there actually is space on the screen to display that line). Any ideas (besides not having a negative margin, which wouldn't look good)?
