### ISSUE TITLE
Center scroller

### ISSUE THREAD

**Issue by SamyPesse** [ajaxorg/ace#2409]
I'm trying to center the `ace-scroller` (not the editor so that using:

```css
.ace_scroller {
      max-width: 900px;
      width: 100%;
      margin: 0px auto;
}
```

But I'm having an issue with the wrap mode, the wrapping is done just like if the width was `100%` (so some part of lines are not visible).

Here is a representation of the issue:
![test](https://cloud.githubusercontent.com/assets/845425/6742149/aede072e-ce8d-11e4-855a-4fd7e4486002.png)

What is the best way to center the scroller ?
