### ISSUE TITLE
CSS validation does not accept variables

### ISSUE THREAD

**Issue by zeropaper** [ajaxorg/ace#3259]
![image](https://cloud.githubusercontent.com/assets/65971/24703276/d8219106-1a02-11e7-819e-940e6933cf59.png)

I am trying to fix that (and provide a PR) but have a hard time figuring where to start.
Any help would be welcome :)

**Comment by BigChief45** [comment]
If I am not mistaken, you could begin by taking a look at [`lib/ace/mode/css/csslint.js`](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/css/csslint.js)

**Comment by zeropaper** [comment]
@BigChief45 I went that far...
actually: https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/css/csslint.js#L3548
but.. it's already line 3000+ (the file has 9000+ lines) and even with breakpoints everywhere.. I can't figure how the whole thing works. :D

**Comment by adamjimenez** [comment]
Think that comes from https://github.com/CSSLint/csslint

**Comment by zeropaper** [comment]
not quite...
I used :root selector because it's a pattern to define variables in :root but those variables could be overrided in a othe selector...

```css
:root {
  --css-var: blue;
}
.selector {
  color: var(--css-var);
}
.other-selector {
  --css-var: green;
}
.other-selector .child {
  color: var(--css-var); /*would be green*/
}
```
