### ISSUE TITLE
Ace ignores styles applied via CSS classes?

### ISSUE THREAD

**Issue by jamesqo** [ajaxorg/ace#3521]
I'm trying out the [embedding tutorial for Ace](https://ace.c9.io/#nav=embedding). If this is my HTML/CSS:

```css
    .codeElement {
        font-family: ..;
        font-size: ..;
    }
```

```html
    <div id="editor" class="codeElement">..code..</div>
```

Then the `font-family` and `font-size` settings are ignored. However, when I write this:

```css
    #editor {
        font-family: ..;
        font-size: ..;
    }
```

```html
    <div id="editor">..code..</div>
```

It works. Why does this happen?
