### ISSUE TITLE
Flickering/overlapping Chinese text during input method composition (IE only)

### ISSUE THREAD

**Issue by huanlin** [ajaxorg/ace#3622]
I recorded an video to show this issue:

https://youtu.be/o1E5il2aFBg

This issue seems happens only with IE. Chrome is fine.

**Comment by huanlin** [comment]
Does anyone have ideas about this issue?
If the video doesn't provide enough information, I can further explain.

**Comment by nightwing** [comment]
looks like ie has a bug applying `background: inherit;` to a textarea, when there is lower precedence rule applying different background.

As a temporary workaround use

```css
.ace_text-input.ace_composition {
    background: white !important;
    color: black !important;
}
```
