### ISSUE TITLE
Gutter gets clipped when scrolling

### ISSUE THREAD

**Issue by zebzhao** [ajaxorg/ace#3651]
Hi again,

Just reporting an issue occurring with the latest commit 8f436eec3a5f6158093761e0016ac451d5397305 and gutter rendering. Scrolling will cut off the bottom part of the gutter. The gutter gets translated up, but its height stays the same as the height of its container. See below:

<img width="245" alt="screen shot 2018-04-18 at 10 13 38 am" src="https://user-images.githubusercontent.com/5515758/38937751-e534389e-42f1-11e8-9889-c56918d69443.png">

Tested with Chrome 65 on MacOS

**Comment by zebzhao** [comment]
Seems like this issue can be fixed by changing the css property of 

```css
.ace_gutter { overflow: visible; }
```

**Comment by zebzhao** [comment]
Found a fix using css:

```css
.ace_gutter {
  overflow: visible !important;
  contain: none !important;
}
```
