### ISSUE TITLE
Rectangle block cursor?

### ISSUE THREAD

**Issue by sandric** [ajaxorg/ace#4023]
I wonder if its possible to change cursor style from vertical bar to rectangle block with specific color. Is it possible/described in docs, link to documentation/example would be great. All I found is
`cursorStyle: "ace"|"slim"|"smooth"|"wide"` option in editor config, but any of this option seems to make nothing for me, so I suggest that's something other.

**Comment by nightwing** [comment]
currently there is no built-in option for this, but the effect can be achieved with css
```js
editor.renderer.$blockCursor = true;
```

```css
.ace_cursor {
    border: none;
    background: #ff0d004f;
}

.ace_hidden-cursors .ace_cursor {
    opacity: 1;
    background: transparent;
    border: 1px #ff0d00ef solid; 
}
```
