### ISSUE TITLE
Multiline placeholder

### ISSUE THREAD

**Issue by doneumark** [ajaxorg/ace#4109]
**Problem**
Defining multiline placeholder is not possible with '/n' chars.
I would like to set a property of a placeholder, that has multiline code segment. but non of the chars I though will make a line break wouldn't work (
, /n, so on...)
How would I be able to achieve that goal?

**Comment by nightwing** [comment]
You can add the following css rule:
```css
.ace_placeholder {
    white-space: pre;
    text-indent: 0;
    margin-left: 10px;
}
```
we'll add this to the default css of ace in the next version
