### ISSUE TITLE
Change text background on hover

### ISSUE THREAD

**Issue by zskumar** [ajaxorg/ace#4298]
Hello! I was wondering if I could get some help with the API. I've added some markers to some lines (tagged as `fullLine` and `inFront` set to true) with the class name `MyHighlight`. The opacity of `MyHighlight` is set to 0.6 initially in CSS. This works fine. What I'd like to do is to change the opacity of each marked line to `1` on mouseenter and back to `0.6` on `mouseleave`. I added this in javascript, but don't see it working when I hover over the lines containing the marker. However, it does work if I force the `hover` state on the div in the chrome developer tools. Is this the right way to do what I want? Here is my code:

``` javascript
var leftElement = document.getElementsByClassName("MyHighlight")[0];
        if (leftElement instanceof HTMLElement) {
            (leftElement as HTMLElement).addEventListener("mouseenter", e => {
                (leftElement as HTMLElement).style.opacity = "1";
            });
            (leftElement as HTMLElement).addEventListener("mouseleave", e => {
                (leftElement as HTMLElement).style.opacity = "0.6";
            });
        }
```

and my css:

``` css
.MyHighlight {
    position: absolute;
    background: rgba(201, 179, 253, 0.3);
    opacity: 0.6;
    z-index: 20
}
```

**Comment by nightwing** [comment]
Using css you can do
```css
.MyHighlight:hover {
   opacity: 0.6;
}

.MyHighlight {
    pointer-events: auto
}
```

or use javascript 

```js
editor.on("mousemove", function(ev) { 
    var {row, column} = ev.getDocumentPosition() 
    // update marker based on row and column
})
```
