### ISSUE TITLE
Incorrect YAML syntax highlighting for version numbers with multiple periods

### ISSUE THREAD

**Issue by rpatrick00** [ajaxorg/ace#4468]
Given a YAML file that looks like this:

```yaml
topology:
    Name: todo_domain
    DomainVersion: 12.2.1.4.0
```
The `DomainVersion` field value is highlighted as a numeric constant instead of a string.

I tested the following regular expression using one of the [online regex testers](https://regex101.com/) and it is not excluding numbers with multiple dots in it.

```javascript
{
    token : "constant.numeric", // float
    regex : /(\b|[+\-\.])[\d_]+(?:(?:\.[\d_]*)?(?:[eE][+\-]?[\d_]+)?)(?=[^\d-\w]|$)/
}
```
