### ISSUE TITLE
Even after using monospace I am still getting cursor at wrong pos.

### ISSUE THREAD

**Issue by PtPrashantTripathi** [ajaxorg/ace#4685]
Hi team, 

I am getting cursor at wrong place, in few of the privious issue which found in here there were mention to add this css
```css
.ace_editor,
.ace_editor * {
    font-family: "Monaco", "Menlo", "Ubuntu Mono", "Droid Sans Mono", "Consolas",
        monospace !important;
    font-size: 13pt !important;
}
```
But even after using this css, we are still facing same issue

I have tried this with different browser and different os as well but same result

![IMG_20220429_234347](https://user-images.githubusercontent.com/26687933/166000254-ad1b7502-6783-4955-a30c-42da723669ff.jpg)

[This website is hosted here, try it you self to reproduce the bug](https://vedic-lang.github.io/vedic-ide)

> Note: instead of English we are type in devnagari, i hope this isn't it creating this issue
