### ISSUE TITLE
color matched tag

### ISSUE THREAD

**Issue by ctuxboy** [ajaxorg/ace#4730]
Hello,
I use the [Caret](https://chrome.google.com/webstore/detail/caret/fljalecfjciodhpcledpamjachpmelml?hl=nl) code-editor on my Chromebook, and using the Monokai-theme.
When select a opened html-tag, it is very difficult see the matched end-tag.
Is there a way, changed the color for this function?
See screenshot below with the **div**-tag by example:
![Screenshot 2022-05-13 11 39 41](https://user-images.githubusercontent.com/10013632/168256929-341325f7-bedd-4028-bf59-b0c71c344656.png)

**Comment by BenSouchet** [comment]
@ctuxboy Hi, you can add custom css to improve lisibility, example:
```CSS
.ace-monokai .ace_marker-layer .ace_bracket {
    border-color: #F8F8F2CC;
    background-color: #202020;
}
```
Ensure this custom CSS is loaded after the ace script or add `!important` to the CSS lines like this:
```CSS
.ace-monokai .ace_marker-layer .ace_bracket {
    border-color: #F8F8F2CC!important;
    background-color: #202020!important;
}
```
