### ISSUE TITLE
Styling Tooltip Base on Gutter Annotation Type

### ISSUE THREAD

**Issue by KiddoV** [ajaxorg/ace#4799]
### Describe the feature

As mention in #4710 . It would be nice to have someway to styling the tooltips.
For example,
When hover the gutter, add a class to tooltip for  styling later:
```css
.ace_tooltip.error {
    color: red;
}
.ace_tooltip.info{
    color: blue;
}
```
Thanks,

### Use Case

To make tooltip match with custom UI theme.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.5.2
