### ISSUE TITLE
support multi-file display for yaml format

### ISSUE THREAD

**Issue by ywager** [ajaxorg/ace#5260]
### Describe the feature

In the following example, multiple yamls are separated by --- characters

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: '2022-12-09T04:33:56Z'
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: '2022-12-09T04:33:56Z'
```

When I try to use multiple yaml files, I modify the yaml first, and the yaml is illegal at this time. When I restore it, the yaml still prompts that it is illegal. I am not sure whether it is because the writing of multiple yaml files is currently not supported.

<img width="1096" alt="image" src="https://github.com/ajaxorg/ace/assets/17868062/a37a7d5a-1d9e-4e01-9f22-5586fbc6b61f">
<img width="482" alt="image" src="https://github.com/ajaxorg/ace/assets/17868062/f5465c66-bbd2-4748-a01f-c0bc53ebde3f">
<img width="958" alt="image" src="https://github.com/ajaxorg/ace/assets/17868062/d413161d-4491-4952-ab22-28bac296d69f">

### Use Case

In our company's products, we use the yaml editor in ace to create k8s resources, and there may be multiple yamls in one editor.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.23.4
