### ISSUE TITLE
Yaml Mode: Missing Fold Widgets on list objects

### ISSUE THREAD

**Issue by robertpatrick** [ajaxorg/ace#5296]
### Describe the bug

When Ace is rendering YAML that contains list elements, the fold widget does not show unless the list is indented.  For example, the following YAML will display without a fold widget on the `properties` line.

```yaml
key: 32782-dtgeudkjes
properties:
- name: abc
  value: 123
- name: def
  value: 456
```
<img width="272" alt="Screenshot 2023-08-30 at 1 40 21 PM" src="https://github.com/ajaxorg/ace/assets/31662131/8124cbb2-3f49-460d-84b5-4db02fcfefb5">

Reformatting the YAML as shown causes the fold widget to appear on the `properties` line.

```yaml
key: 32782-dtgeudkjes
properties:
  - name: abc
    value: 123
  - name: def
    value: 456
```

<img width="275" alt="Screenshot 2023-08-30 at 1 41 17 PM" src="https://github.com/ajaxorg/ace/assets/31662131/41a7dd29-0b7c-4cae-88c6-db4165a771c4">

Unfortunately, a lot of YAML tools generate lists without the indention so this is pretty egregious bug. 

### Expected Behavior

I expect the fold widget to appear on the list object regardless of how the list is indented.

### Current Behavior

The list object has no fold widget if the list is not indented but does if the list is indented.

### Reproduction Steps

Drop the YAML snippets above in the editor and observe the fold widgets, as shown in the screen shots.

### Possible Solution

Indentation on subsequent lines cannot be the only thing that determines whether an object gets a fold widget or not.  For situations where there is no indentation, the code needs to check for `- ` (hyphen followed by a space) which would indicate that the line belongs to the list object defined above.

### Ace Version / Browser / OS / Keyboard layout

ace-builds@1.24.1, Chrome and Firefox, MacOS, US Keyboard layout
